#!/bin/zsh
PGM=$1
SEP=$2
INPUT=$3
NIN=`cat $INPUT | wc -l`
echo "\tOUTPUT\n" > out.txt
./$PGM < $INPUT >> out.txt
NOUT=`cat out.txt | wc -l`
D=$(( NOUT/(NIN+1)-1 ))
echo "INPUT\n" > aux.in
cat $INPUT >> aux.in
: << 'COMMENT'
# Por si quiero que el código se repita varias veces
for ((a=1;a<$D;a++)); do
    echo "-------------------------" >> aux.in
    cat $INPUT >> aux.in
done
COMMENT
pr -m -t aux.in out.txt
rm out.txt aux.in
#echo $NOUT $NIN $D