#!/bin/bash
PGM=$1
SEP=$2
INPUT=$3
NIN=`cat $INPUT | wc -l`
echo "\nOUTPUT\n" > out.txt
java -cp . $PGM < $INPUT >> out.txt
NOUT=`cat out.txt | wc -l`
D=$(( NOUT/(NIN+1)-1 ))
echo "\nINPUT\n" > aux.in
cat $INPUT >> aux.in
for ((a=1;a<$D;a++)); do 
    echo "-------------------------" >> aux.in
    cat $INPUT >> aux.in
done
pr -m -t aux.in out.txt
rm out.txt aux.in
#echo $NOUT $NIN $D
