PARSER_BEGIN(expr2maqPila)

public class expr2maqPila{

  public static void main(String args[]) throws ParseException {
    expr2maqPila parser = new expr2maqPila(System.in);
    parser.ExpressionList();
  }

}

PARSER_END(expr2maqPila)

SKIP :
{
  " " | "\t" | "\n" | "\r"
}

TOKEN :
{
  < NUM: ( ["0"-"9"] )+ >
}

void ExpressionList() :
{
  String res;
}
{
  ( res=Expression() ";" { System.out.println("=\n"+res); }
  )*
  <EOF>
}

String Expression() :
{
  String res, val;
}
{
  res=Term()
  ( 
   "+" val=Term()  { res=res+"\n"+val+"\nadd"; }
   |
   "-" val=Term()  { res=res+"\n"+val+"\nsub"; }
  )*
  { return res; }
}

String Term() :
{
  String res, val;
  Token tk;
}
{
  res=Factor()
  ( 
    "*" val=Factor() { res=res+"\n"+val+"\nmul"; }
    |
    "/" val=Factor() { res=res+"\n"+val+"\ndiv"; }
  )*
  { return res; }
}

String Factor() :
{
  Token tk;
  String res;
}
{
 ( tk=<NUM> { res=tk.image; }
   |
  "(" res=Expression() ")"
 ) { return res; }
}
